-   id: refs_control
    name: Refs Checker
    description: Enforces the commit message has Refs in footer section
    entry: refs_control.sh
    language: script
    always_run: true
-   id: type_control
    name: Type Checker
    description: Enforces the commit message has ci/build in case of ci/build files
    entry: type_control.sh
    language: script
    always_run: true
-   id: commitizen
    name: commitizen check
    entry: pipenv run cz check
    language: system
    args: [--allow-abort, --commit-msg-file]